# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265358979
    has_acceleration_limits: true
    max_acceleration: 11.4043303983813 
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.87979326579064
    has_acceleration_limits: true
    max_acceleration: 9.70403064108847
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.45575191894877
    has_acceleration_limits: true
    max_acceleration: 10.9706160792608
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.31968989868597
    has_acceleration_limits: true
    max_acceleration: 11.8366484541003
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.31968989868597
    has_acceleration_limits: true
    max_acceleration: 11.1404366154798
  joint_6:
    has_velocity_limits: true
    max_velocity: 6.91150383789755
    has_acceleration_limits: true
    max_acceleration: 14.0368105091644
  palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
